"""add_dashboard_layout_to_users

Revision ID: f28595157a94
Revises: ab696fc771ed
Create Date: 2026-06-18 11:31:49.948043
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f28595157a94'
down_revision = 'ab696fc771ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dashboard_layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard_layout')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
