#!/bin/bash
# Quick Kaggle Setup Script for R-DIOS

echo "🔑 Kaggle API Setup for R-DIOS"
echo "=============================="
echo ""
echo "You need a Kaggle account and API token to download datasets."
echo ""
echo "📋 Quick Setup Steps:"
echo ""
echo "1️⃣  Go to: https://www.kaggle.com/settings"
echo "   (Sign up for free if you don't have an account)"
echo ""
echo "2️⃣  Scroll down to the 'API' section"
echo ""
echo "3️⃣  Click 'Create New Token' button"
echo "   This will download 'kaggle.json' to your Downloads folder"
echo ""
echo "4️⃣  Open a NEW terminal and run:"
echo ""
echo "   mkdir -p ~/.kaggle"
echo "   cp ~/Downloads/kaggle.json ~/.kaggle/"
echo "   chmod 600 ~/.kaggle/kaggle.json"
echo ""
echo "5️⃣  Return here and run: ./scripts/download_datasets.sh"
echo ""
echo "💡 The kaggle.json file contains your API credentials"
echo "   Keep it secure and don't share it!"
echo ""
