"""Retrieval over the project's own documentation (RAG without a vector database).

The corpus is the Markdown files in docs/knowledge (glossary, forecasting, imports, dataset, anomalies,
invoices, assistant, data dictionary), split into "## " sections, plus short documents generated from the
database: dataset provenance and one summary per outlet. Retrieval is TF-IDF with cosine similarity -
deterministic, dependency-free and fast for a corpus of this size. Answers quote the matching sections and
name their source; nothing is retrieved from outside the project.
"""
from __future__ import annotations

import math
import re
import threading
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.config import settings
from app.services.assistant.nlu import _stem

STOPWORDS = set("""a an and are as at be by can do does for from has have how i in into is it its me my of on or our
so than that the their them then there these this to us was we were what when where which who why will with you your
about tell explain mean means meaning define definition please show give""".split())
MIN_SCORE = 0.12
# a few everyday words mapped to the vocabulary the documentation uses
EXPANSIONS = {"real": "synthetic demo", "fake": "synthetic demo", "come": "source generated", "made": "generated",
              "accurate": "error wape", "accuracy": "error wape", "upload": "import csv", "csv": "import",
              "band": "interval", "range": "interval", "unusual": "anomal", "spike": "anomal", "outlier": "anomal",
              "tax": "gst", "bill": "invoice", "seed": "reproducibility"}


@dataclass
class Doc:
    source: str
    title: str
    text: str


def _root(word: str) -> str:
    """Light suffix stripping on top of the plural stemmer: importing / imported / imports -> import."""
    for suffix in ("ations", "ation", "ing", "ies", "ed", "es"):
        if len(word) - len(suffix) >= 4 and word.endswith(suffix):
            word = word[: -len(suffix)] + ("y" if suffix == "ies" else "")
            break
    return _stem(word)


def _tokens(text: str, expand: bool = False) -> list[str]:
    words = [w for w in re.findall(r"[a-z0-9]+", text.lower()) if w not in STOPWORDS and len(w) > 1]
    if expand:
        words += [x for w in words for x in EXPANSIONS.get(w, "").split()]
    return [_root(w) for w in words]


def _static_docs() -> list[Doc]:
    docs = []
    root = Path(settings.KNOWLEDGE_DIR)
    for path in sorted(root.glob("*.md")) if root.exists() else []:
        text = path.read_text(encoding="utf-8")
        doc_title = (re.search(r"^# (.+)$", text, re.M) or [None, path.stem])[1]
        for part in re.split(r"^## ", text, flags=re.M)[1:]:
            heading, _, body = part.partition("\n")
            docs.append(Doc(f"docs/knowledge/{path.name}", f"{doc_title}: {heading.strip()}", body.strip()))
    return docs


def _dynamic_docs(db: Session) -> list[Doc]:
    from app.models import DatasetInfo, Outlet, Sale
    from app.services import analytics as A

    docs = []
    ds = db.scalar(select(DatasetInfo).order_by(DatasetInfo.id.desc()))
    sources = dict(db.execute(select(Sale.source, func.count(Sale.id)).group_by(Sale.source)).all())
    first, last = A.first_sale_date(db), A.latest_sale_date(db)
    text = (f"The database holds {sum(sources.values()):,} bills from {first} to {last}: "
            + ", ".join(f"{n:,} {s}" for s, n in sorted(sources.items())) + ".")
    if ds:
        text += (f" The synthetic part was generated by generator version {ds.generator_version} with random seed "
                 f"{ds.random_seed} on {ds.generated_at:%Y-%m-%d}, covering {ds.period_start} to {ds.period_end}.")
    docs.append(Doc("database: dataset_info", "Current dataset metadata (source, seed, period)", text))
    for o in db.scalars(select(Outlet).order_by(Outlet.id)).all():
        docs.append(Doc("database: outlets", f"Outlet {o.code} - {o.name}",
                        f"{o.name} ({o.code}) is in {o.city}, {o.state or ''}, opened on {o.opened_on}. Manager: "
                        f"{o.manager_name or 'not set'}. Status: {'active' if o.is_active else 'inactive'}."))
    return docs


class _Index:
    def __init__(self, docs: list[Doc]):
        self.docs = docs
        tf = [self._counts(_tokens(d.title + " " + d.title + " " + d.text)) for d in docs]
        df: dict[str, int] = {}
        for counts in tf:
            for t in counts:
                df[t] = df.get(t, 0) + 1
        n = len(docs)
        self.idf = {t: math.log((1 + n) / (1 + c)) + 1 for t, c in df.items()}
        self.vecs = [self._weigh(c) for c in tf]

    @staticmethod
    def _counts(tokens: list[str]) -> dict[str, float]:
        out: dict[str, float] = {}
        for t in tokens:
            out[t] = out.get(t, 0) + 1
        return out

    def _weigh(self, counts: dict[str, float]) -> dict[str, float]:
        v = {t: (1 + math.log(c)) * self.idf.get(t, 0.0) for t, c in counts.items()}
        norm = math.sqrt(sum(x * x for x in v.values())) or 1.0
        return {t: x / norm for t, x in v.items()}

    def search(self, query: str, k: int) -> list[tuple[float, Doc]]:
        q = self._weigh(self._counts(_tokens(query, expand=True)))
        scored = [(sum(w * vec.get(t, 0.0) for t, w in q.items()), d) for vec, d in zip(self.vecs, self.docs, strict=True)]
        return sorted([s for s in scored if s[0] > 0], key=lambda s: -s[0])[:k]


_lock = threading.Lock()
_static: list[Doc] | None = None


def search(db: Session, query: str, k: int = 3) -> list[dict]:
    global _static
    with _lock:
        if _static is None:
            _static = _static_docs()
    index = _Index(_static + _dynamic_docs(db))
    return [{"score": round(s, 3), "source": d.source, "title": d.title, "text": d.text}
            for s, d in index.search(query, k)]


def best_match(db: Session, query: str) -> list[dict]:
    """Relevant sections, or [] when nothing in the documentation matches well enough."""
    hits = search(db, query, 3)
    if not hits or hits[0]["score"] < MIN_SCORE:
        return []
    return [h for h in hits if h["score"] >= max(MIN_SCORE, hits[0]["score"] * 0.6)][:2]
