"""Driver analysis: why did revenue change between two periods?

Every number here is computed from the database; nothing is generated by a language model.

1. Traffic vs basket (exact decomposition)   dR = (N1 - N0) * AOV0  +  N1 * (AOV1 - AOV0)
   N = completed bills, AOV = average bill value. The two parts add up to the full change.
2. Where it happened                         change per outlet and per category (they each add up to dR).
3. Calendar mix                              expected change from the weekday mix and festival days alone,
                                             using the outlets' weekday profile from the previous 26 weeks.
4. Promotions                                revenue on promoted lines in each period, and the discount given.
5. Stockouts                                 estimated revenue lost while products were out of stock
                                             (days out x the product's normal daily revenue at that outlet).
6. Weather (association, not causation)      log revenue vs rainfall regression on the past year, applied to the
                                             difference in rainfall between the periods.
7. Anomalies                                 unusual outlet-days inside each period (see services/anomalies.py).

Without an explicit comparison period the baseline is like-for-like (A.comparable_period): the same weekdays a week
earlier for periods up to a week, the same days of the previous month for month-to-date, otherwise the preceding
period of equal length. If the comparison period has a different length, its totals are scaled.
"""
from __future__ import annotations

from datetime import date, timedelta

import numpy as np
import pandas as pd
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import Category, Outlet, Product, Promotion, Sale, SaleItem, StockoutEvent, WeatherDaily
from app.services import analytics as A
from app.services import anomalies as AN
from app.services.holidays import event_window


def _totals(db: Session, rng: A.DateRange, outlet_ids: list[int] | None) -> tuple[float, int]:
    rev, bills = db.execute(select(func.coalesce(func.sum(Sale.total), 0), func.count(Sale.id)).where(
        *A._sale_filters(rng, outlet_ids))).one()
    return float(rev), int(bills)


def _by(db: Session, rng: A.DateRange, outlet_ids: list[int] | None, key) -> dict:
    if key == "outlet":
        q = select(Sale.outlet_id, func.sum(Sale.total)).where(*A._sale_filters(rng, outlet_ids)).group_by(Sale.outlet_id)
    else:
        q = A._item_query(rng, outlet_ids, Product.category_id, func.sum(SaleItem.line_total)).join(
            Product, Product.id == SaleItem.product_id).group_by(Product.category_id)
    return {k: float(v) for k, v in db.execute(q).all()}


def _daily(db: Session, start: date, end: date, outlet_ids: list[int] | None) -> pd.Series:
    rows = db.execute(select(Sale.sale_date, func.sum(Sale.total)).where(
        *A._sale_filters(A.DateRange(start, end), outlet_ids)).group_by(Sale.sale_date)).all()
    idx = pd.date_range(start, end, freq="D")
    if not rows:
        return pd.Series(0.0, index=idx)
    s = pd.Series({pd.Timestamp(d): float(v) for d, v in rows})
    return s.reindex(idx, fill_value=0.0)


def _calendar_effect(db: Session, cur: A.DateRange, cmp: A.DateRange, outlet_ids: list[int] | None,
                     cmp_revenue: float) -> dict:
    """Change explained by the weekday mix + festival days, holding everything else constant."""
    hist = _daily(db, cmp.start - timedelta(days=182), cmp.start - timedelta(days=1), outlet_ids)
    hist = hist[hist > 0]
    if len(hist) < 56:
        return {"effect": 0.0, "note": "Not enough history to estimate weekday and festival effects."}
    plain = hist[[event_window(d.date()) is None for d in hist.index]]
    wd = plain.groupby(plain.index.dayofweek).mean()
    wd = wd / wd.mean()
    fest = hist[[event_window(d.date()) is not None for d in hist.index]]
    fest_lift = 1.0
    if len(fest) >= 5:
        fest_lift = float((fest / fest.index.dayofweek.map(wd).values).mean() / (plain / plain.index.dayofweek.map(wd).values).mean())

    def weight(r: A.DateRange) -> tuple[float, int]:
        days = pd.date_range(r.start, r.end, freq="D")
        f = [wd.get(d.dayofweek, 1.0) * (fest_lift if event_window(d.date()) else 1.0) for d in days]
        return float(np.mean(f)), sum(1 for d in days if event_window(d.date()))

    w1, f1 = weight(cur)
    w0, f0 = weight(cmp)
    effect = cmp_revenue * (w1 / w0 - 1) if w0 else 0.0
    weekends = lambda r: sum(1 for d in pd.date_range(r.start, r.end, freq="D") if d.dayofweek >= 5)  # noqa: E731
    return {"effect": round(effect, 2), "weekend_days": [weekends(cur), weekends(cmp)],
            "festival_days": [f1, f0], "festival_lift": round(fest_lift, 3)}


def _promotions(db: Session, rng: A.DateRange, outlet_ids: list[int] | None) -> dict:
    """Promoted-line revenue and its estimated uplift over the same products' normal (pre-period) sales."""
    rows = db.execute(A._item_query(
        rng, outlet_ids, SaleItem.outlet_id, SaleItem.product_id, func.min(SaleItem.sale_date),
        func.max(SaleItem.sale_date), func.sum(SaleItem.line_total),
        func.coalesce(func.sum((SaleItem.list_price - SaleItem.unit_price) * SaleItem.quantity), 0)).where(
        SaleItem.promotion_id.is_not(None)).group_by(SaleItem.outlet_id, SaleItem.product_id)).all()
    base = A.DateRange(rng.start - timedelta(days=28), rng.start - timedelta(days=1))
    normal = {(o, p): float(v) / 28 for o, p, v in db.execute(A._item_query(
        base, outlet_ids, SaleItem.outlet_id, SaleItem.product_id, func.sum(SaleItem.line_total)).where(
        SaleItem.promotion_id.is_(None)).group_by(SaleItem.outlet_id, SaleItem.product_id)).all()}
    rev = disc = uplift = 0.0
    for o, p, first, last, total, discount in rows:
        days = (last - first).days + 1
        rev += float(total)
        disc += float(discount)
        uplift += float(total) - normal.get((o, p), 0.0) * days
    names = db.scalars(select(Promotion.name).where(Promotion.start_date <= rng.end, Promotion.end_date >= rng.start)
                       ).all()
    return {"revenue": round(rev, 2), "uplift": round(uplift, 2), "discount_given": round(disc, 2),
            "running": list(names)}


def _stockout_loss(db: Session, rng: A.DateRange, outlet_ids: list[int] | None) -> dict:
    q = select(StockoutEvent).where(StockoutEvent.end_date >= rng.start, StockoutEvent.start_date <= rng.end)
    if outlet_ids:
        q = q.where(StockoutEvent.outlet_id.in_(outlet_ids))
    events = db.scalars(q).all()
    if not events:
        return {"lost_revenue": 0.0, "events": 0, "product_days": 0, "top": []}
    # normal daily revenue per (outlet, product) over the 28 days before the period
    base = A.DateRange(rng.start - timedelta(days=28), rng.start - timedelta(days=1))
    rate = {(o, p): float(v) / 28 for o, p, v in db.execute(A._item_query(
        base, outlet_ids, SaleItem.outlet_id, SaleItem.product_id, func.sum(SaleItem.line_total)).group_by(
        SaleItem.outlet_id, SaleItem.product_id)).all()}
    names = dict(db.execute(select(Product.id, Product.name)).all())
    lost, days_total, per_product = 0.0, 0, {}
    for e in events:
        days = (min(e.end_date, rng.end) - max(e.start_date, rng.start)).days + 1
        # substitutes recover part of the demand; count 60% of the normal revenue as lost when one exists
        share = 0.4 if e.substitute_product_id else 1.0
        amount = rate.get((e.outlet_id, e.product_id), 0.0) * days * share
        lost += amount
        days_total += days
        per_product[names.get(e.product_id)] = per_product.get(names.get(e.product_id), 0.0) + amount
    top = sorted(per_product.items(), key=lambda kv: -kv[1])[:5]
    return {"lost_revenue": round(lost, 2), "events": len(events), "product_days": days_total,
            "top": [{"product": k, "lost_revenue": round(v, 2)} for k, v in top]}


def _weather(db: Session, cur: A.DateRange, cmp: A.DateRange, outlet_ids: list[int] | None,
             cur_revenue: float) -> dict:
    oq = select(Outlet.city)
    if outlet_ids:
        oq = oq.where(Outlet.id.in_(outlet_ids))
    cities = list(set(db.scalars(oq).all()))
    if not cities:
        return {"effect": 0.0}
    start = cmp.start - timedelta(days=365)
    rain = pd.DataFrame(db.execute(select(WeatherDaily.day, func.avg(WeatherDaily.rain_mm)).where(
        WeatherDaily.city.in_(cities), WeatherDaily.day >= start, WeatherDaily.day <= cur.end).group_by(
        WeatherDaily.day)).all(), columns=["day", "rain"])
    if rain.empty:
        return {"effect": 0.0, "note": "No weather data."}
    rain = rain.set_index(pd.to_datetime(rain["day"]))["rain"].astype(float).sort_index()  # PostgreSQL: unordered
    hist = _daily(db, start, cmp.start - timedelta(days=1), outlet_ids)
    hist = hist[hist > 0]
    beta = 0.0
    if len(hist) >= 120:
        # de-seasonalise: divide by a centred 4-week rolling mean of same-weekday values
        logr = np.log(hist)
        base = logr.groupby(logr.index.dayofweek).transform(lambda s: s.rolling(5, center=True, min_periods=3).median())
        resid = (logr - base).dropna()
        r = rain.reindex(resid.index).fillna(0.0).clip(upper=60)
        if r.var() > 0:
            beta = float(np.cov(r, resid)[0, 1] / r.var())
    def mean_rain(r: A.DateRange) -> float:
        v = rain.loc[pd.Timestamp(r.start):pd.Timestamp(r.end)].mean()
        return float(v) if pd.notna(v) else 0.0

    heavy = lambda r: int((rain.loc[pd.Timestamp(r.start):pd.Timestamp(r.end)] >= AN.HEAVY_RAIN_MM).sum())  # noqa: E731
    r1, r0 = mean_rain(cur), mean_rain(cmp)
    effect = cur_revenue * (1 - np.exp(-beta * (min(r1, 60) - min(r0, 60)))) if beta and np.isfinite(beta) else 0.0
    return {"effect": round(float(effect), 2), "rain_mm_per_day": [round(r1, 1), round(r0, 1)],
            "heavy_rain_days": [heavy(cur), heavy(cmp)], "pct_per_10mm": round(float(np.exp(beta * 10) - 1) * 100, 1),
            "note": "Association estimated from the past year of data, not a causal effect."}


@A.cached
def explain_change(db: Session, cur_start: date, cur_end: date, cmp_start: date | None = None,
                   cmp_end: date | None = None, outlet_ids: list[int] | None = None) -> dict:
    cur = A.DateRange(cur_start, cur_end)
    cmp = A.DateRange(cmp_start, cmp_end) if cmp_start and cmp_end else A.comparable_period(cur)[0]
    scale = cur.days / cmp.days

    r1, n1 = _totals(db, cur, outlet_ids)
    r0_raw, n0_raw = _totals(db, cmp, outlet_ids)
    r0, n0 = r0_raw * scale, n0_raw * scale
    out = {"period": cur.as_dict(), "comparison": cmp.as_dict(), "scaled": scale != 1,
           "revenue": [round(r1, 2), round(r0, 2)], "bills": [n1, round(n0)],
           "change": round(r1 - r0, 2), "change_pct": A.pct_change(r1, r0)}
    if not n1 or not n0:
        out.update(insufficient_data=True, drivers=[], summary=[
            "There are no completed sales in one of the two periods, so the change cannot be explained."])
        return out

    aov0, aov1 = r0 / n0, r1 / n1
    traffic, basket = (n1 - n0) * aov0, n1 * (aov1 - aov0)
    out["avg_bill"] = [round(aov1, 2), round(aov0, 2)]

    names = A.outlet_names(db)
    o1, o0 = _by(db, cur, outlet_ids, "outlet"), _by(db, cmp, outlet_ids, "outlet")
    outlets = sorted(({"outlet_id": k, "outlet": names.get(k, str(k)), "current": round(o1.get(k, 0), 2),
                       "previous": round(o0.get(k, 0) * scale, 2),
                       "change": round(o1.get(k, 0) - o0.get(k, 0) * scale, 2),
                       "change_pct": A.pct_change(o1.get(k, 0), o0.get(k, 0) * scale)}
                      for k in set(o1) | set(o0)), key=lambda r: r["change"])
    cat_names = dict(db.execute(select(Category.id, Category.name)).all())
    c1, c0 = _by(db, cur, outlet_ids, "category"), _by(db, cmp, outlet_ids, "category")
    categories = sorted(({"category_id": k, "category": cat_names.get(k, "Uncategorised"),
                          "current": round(c1.get(k, 0), 2), "previous": round(c0.get(k, 0) * scale, 2),
                          "change": round(c1.get(k, 0) - c0.get(k, 0) * scale, 2),
                          "change_pct": A.pct_change(c1.get(k, 0), c0.get(k, 0) * scale)}
                         for k in set(c1) | set(c0)), key=lambda r: r["change"])

    calendar = _calendar_effect(db, cur, cmp, outlet_ids, r0)
    p1, p0 = _promotions(db, cur, outlet_ids), _promotions(db, cmp, outlet_ids)
    s1, s0 = _stockout_loss(db, cur, outlet_ids), _stockout_loss(db, cmp, outlet_ids)
    weather = _weather(db, cur, cmp, outlet_ids, r1)
    an_cur = [a for a in AN.detect(db, cur.start, cur.end, outlet_ids) if not a.get("explained_by")]
    an_cmp = [a for a in AN.detect(db, cmp.start, cmp.end, outlet_ids) if not a.get("explained_by")]
    an_effect = sum(a["impact"] for a in an_cur) - sum(a["impact"] for a in an_cmp) * scale

    drivers = [
        {"key": "traffic", "label": "Number of bills (footfall)", "effect": round(traffic, 2),
         "detail": f"{n1:,} bills vs {n0:,.0f} ({A.pct_change(n1, n0):+.1f}%)" if n0 else None},
        {"key": "basket", "label": "Average bill value", "effect": round(basket, 2),
         "detail": f"₹{aov1:,.0f} vs ₹{aov0:,.0f}"},
        {"key": "calendar", "label": "Weekday mix and festivals", "effect": calendar["effect"],
         "detail": (f"festival days {calendar['festival_days'][0]} vs {calendar['festival_days'][1]}, weekend days "
                    f"{calendar['weekend_days'][0]} vs {calendar['weekend_days'][1]}") if "weekend_days" in calendar
         else calendar.get("note")},
        {"key": "promotions", "label": "Promotions (estimated uplift)",
         "effect": round(p1["uplift"] - p0["uplift"] * scale, 2),
         "detail": f"uplift {_signed(p1['uplift'])} vs {_signed(p0['uplift'] * scale)}; "
                   f"{len(p1['running'])} vs {len(p0['running'])} promotion(s)"},
        {"key": "stockouts", "label": "Stockouts (estimated lost sales)",
         "effect": round(-(s1["lost_revenue"] - s0["lost_revenue"] * scale), 2),
         "detail": f"₹{s1['lost_revenue']:,.0f} lost vs ₹{s0['lost_revenue'] * scale:,.0f}"},
        {"key": "weather", "label": "Rainfall (association)", "effect": weather["effect"],
         "detail": (f"{weather['rain_mm_per_day'][0]} vs {weather['rain_mm_per_day'][1]} mm/day; heavy-rain days "
                    f"{weather['heavy_rain_days'][0]} vs {weather['heavy_rain_days'][1]}")
         if "rain_mm_per_day" in weather else weather.get("note")},
        {"key": "anomalies", "label": "Unusual days (outages, bulk orders, errors)", "effect": round(an_effect, 2),
         "detail": f"{len(an_cur)} unusual outlet-day(s) vs {len(an_cmp)}"},
    ]
    out.update(
        insufficient_data=False, decomposition={"traffic": round(traffic, 2), "basket": round(basket, 2)},
        drivers=drivers, outlets=outlets, categories=categories, calendar=calendar,
        promotions={"current": p1, "previous": p0}, stockouts={"current": s1, "previous": s0}, weather=weather,
        anomalies=[{**a, "explanation": AN.explain(db, a)} for a in an_cur],
    )
    out["summary"] = _summary(out)
    return out


def _signed(v: float) -> str:
    return f"{'-' if v < 0 else ''}₹{abs(v):,.0f}"


def _money(v: float) -> str:
    return f"₹{abs(v):,.0f}"


def summary_lines(r: dict, money=_money) -> list[str]:
    """Plain-language summary of an explain_change() result; `money` formats an absolute amount."""
    return _summary(r, money)


def _summary(r: dict, _money=_money) -> list[str]:
    ch = r["change"]
    direction = "up" if ch >= 0 else "down"
    pct = f" ({r['change_pct']:+.1f}%)" if r["change_pct"] is not None else ""
    lines = [f"Revenue is {direction} {_money(ch)}{pct}: {_money(r['revenue'][0])} vs {_money(r['revenue'][1])}."]
    d = r["decomposition"]
    lines.append(f"{'More' if d['traffic'] >= 0 else 'Fewer'} bills account for {'+' if d['traffic'] >= 0 else '-'}"
                 f"{_money(d['traffic'])}, a {'higher' if d['basket'] >= 0 else 'lower'} average bill for "
                 f"{'+' if d['basket'] >= 0 else '-'}{_money(d['basket'])}.")
    worst = r["outlets"][0] if ch < 0 else r["outlets"][-1]
    if len(r["outlets"]) > 1 and worst["change"] * ch > 0:
        lines.append(f"Largest contribution by outlet: {worst['outlet']} ({'+' if worst['change'] >= 0 else '-'}"
                     f"{_money(worst['change'])}).")
    cat = r["categories"][0] if ch < 0 else r["categories"][-1]
    if r["categories"] and cat["change"] * ch > 0:
        lines.append(f"Largest contribution by category: {cat['category']} ({'+' if cat['change'] >= 0 else '-'}"
                     f"{_money(cat['change'])}).")
    context = [x for x in r["drivers"] if x["key"] not in ("traffic", "basket") and abs(x["effect"]) >= 0.01 * max(
        abs(r["revenue"][1]), 1)]
    for x in sorted(context, key=lambda x: -abs(x["effect"]))[:3]:
        lines.append(f"{x['label']}: about {'+' if x['effect'] >= 0 else '-'}{_money(x['effect'])} ({x['detail']}).")
    return lines
